### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by ergopix** [msigley/WP-Instagram-API#3]
I use this tool here: https://www.bejart.ch/

But for some time now, I don't have any images returned since Instagram.

Thanks!

Jonathane

**Comment by msigley** [comment]
The credentials on the instagram account probably changed. Deactivate and reactivate the plugin, then re-authorize your instagram account.

**Comment by msigley** [comment]
If this happens often, it is an indication your site isn't getting enough traffic to keep the instagram access token refresh and valid. The access token refresh works off of WP Cron, so I would recommend running WP Cron as a scheduled task as outlined here:
https://developer.wordpress.org/plugins/cron/hooking-wp-cron-into-the-system-task-scheduler/

This could also be an indication you have hit the API call limit. If this site isn't using an object cache plugin, set one up to allow instagram API calls to be cached. I maintain an object cache plugin you could use for this as well:
https://github.com/msigley/WP-Simple-Object-Cache

**Comment by msigley** [comment]
@ergopix I identified and fixed an issue with the access token refreshing that would cause issues like what you experienced. Please try v2.0.1 and let me know if you continue to have problems.
