### ISSUE TITLE
Instagram Wordpress API: Bad or missing user access token.

### ISSUE THREAD

**Issue by adambichler** [msigley/WP-Instagram-API#4]
I'm getting this error: "Instagram Wordpress API: Bad or missing user access token. Please reauthenicate with Instagram to pull and display content from Instagram." If I click the link right there, I'm redirected to instagram where I have to allow access. Then I'm back in WP, but nothing changed.

I have set the "https://yourdomain.com/wp-admin/" as a valid OAuth Redirect URI, but the error is still there. Not sure what I am missing. 

In my WP Config fiel I set the following two lines:
define('INSTAGRAM_CLIENT_ID', '<your instagram app id>');
define('INSTAGRAM_CLIENT_SECRET', '<your instagram app secret>');

Which of the IDs should I use? "App ID" (at top of developer page) or "Instagram-App-ID" (found under Instagram Basic Display)?

Any ideas? Thanks!

**Comment by msigley** [comment]
The client ID and client secret must be filled in those defines from your facebook developer account:
https://developers.facebook.com/docs/instagram-basic-display-api/getting-started

**Comment by adambichler** [comment]
Hey @msigley,
Sure, I set them like this, right:
define('INSTAGRAM_CLIENT_ID', '14445690XXXXX138');
define('INSTAGRAM_CLIENT_SECRET','IGQVJWbkNONnhkUlXXXXXXjRYaF9kRDc2RGdLNDlTYnViRWx6TAHVSDHdvsvshYTlYxTUtXZATczVmXXXXXXXjMzUy1BNERhbEpNcUF6aDVBSnJXXXXX0hMeHlMZAVJ5clo2VEdIMgZDZD');
That's what I did, but it didn't work. Thanks for your reply
