### ISSUE TITLE
Object caching

### ISSUE THREAD

**Issue by oraaa17** [msigley/WP-Instagram-API#5]
This plugin uses WP Object cache to store results of API call. Is it possible to make use of transient API instead? From my understanding if I don't have access from my hosting provider to persistent object caching like redis, I don't really take advantage of wp_cache_set unless I need this data to use several times across one page. So it's maybe better idea to store data in database via transients and from there load it to several users? To further improve it I think to add cron job (on server) for making this calls once a day and store response in database. What do you think about it. I'm new to PHP and WordPress and looking for opinion.

Did you think abot how could be implemented image resizing of images from Instagram? Images from response are too big and not in webp format. Could adding them via media uploader to WordPress be good solution?

**Comment by msigley** [comment]
Almost all reputable hosts have some form of memory caching available to use with the Wordpress Object Cache system:
https://developer.wordpress.org/reference/classes/wp_object_cache/#persistent-cache-plugins

On budget shared hosting, it may not be available so I would suggest using a file based Wordpress Object Cache drop in. I have used this one in the past with Inmotion hosting:
https://github.com/emrikol/focus
On budget shared hosting the database is actually the bottleneck to site speed so using a file based drop in makes sense.

The Instagram API used to provide several image sizes when requesting posts. When Facebook moved Instagram over to the "Basic Display API" they removed the additional image sizes. If you have documentation on query parameters to pass to Instagram in the image urls, I would look at adding this feature, but the last time I looked at this Instagram used encrypted query parameters on its site.

You can implement image lazy loading on your website to mitigate the image size issue:
https://github.com/msigley/WP-Simple-Lazy-Load
