### ISSUE TITLE
Question with this Plugin

### ISSUE THREAD

**Issue by davidmedia** [msigley/WP-Instagram-API#7]
Hey,
can u provide something similat like that? 
its a a form that can check the username and lists the postings. you can define and select etc..
you maybe know a plugin or solution for it. Please help.

**Comment by msigley** [comment]
No. Ive removed the links in you comment. 

Scraping instagram accounts that you dont own is against their terms of service and so is buying fake likes to artifically inflate your like count. Building likes/follows/subscribes in social media is a grind and it will not happen overnight. I suggest you produce content people enjoy and the likes will come naturally.
